const paragraph = [
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
  "My family lived in a mountain village; our people, the Pragonese, worshipped the sky as the spiritual home of the gods and the higher you lived, the closer you were to them.  Our planet’s name, Elavan, literally means ‘mountain pathway,’ and every night our prayer rituals involved us looking at the skyline for a sign the gods may give us, a fluttering star, a cool breeze – anything that could be a message of divinity.",
];

export default paragraph;
